import { logArrowFunction } from './arrow-function/index';
import { logDestructuringObject, logDestructuringArry } from './destructuring/index';
import { logTemplateString } from './template-string/index';
import { logRest } from './rest/index';
import { logSpread } from './spread/index';
import { logParameters } from './default-parameters/index';
import { logConst } from './const/index';
import { logLet } from './let/index';
import { logMap } from './map/index';
import { logFilter } from './filter/index';

logArrowFunction();
logDestructuringObject();
logDestructuringArry();
logTemplateString();
logRest();
logSpread();
logParameters();
logConst();
logLet();
logMap();
logFilter();